# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "pwm"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Nicholas E. Rabenau"]
  s.date = "2012-03-12"
  s.description = "pwm is a secure password manager for the commandline"
  s.email = "nerab@gmx.net"
  s.executables = ["pwm", "pwm"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/pwm",
    "lib/pwm.rb",
    "lib/pwm/dialog.rb",
    "lib/pwm/dialog/base.rb",
    "lib/pwm/dialog/cocoa.rb",
    "lib/pwm/dialog/console.rb",
    "lib/pwm/dialog/gnome.rb",
    "lib/pwm/message.rb",
    "lib/pwm/password_policy.rb",
    "lib/pwm/store.rb",
    "templates/export.html.erb",
    "test/acceptance/test_basics.rb",
    "test/acceptance/test_delete.rb",
    "test/acceptance/test_dialogs.rb",
    "test/acceptance/test_export.rb",
    "test/acceptance/test_get.rb",
    "test/acceptance/test_init.rb",
    "test/acceptance/test_list.rb",
    "test/acceptance/test_passwd.rb",
    "test/acceptance/test_put.rb",
    "test/fixtures/test_all.html",
    "test/fixtures/test_empty.html",
    "test/helper.rb",
    "test/unit/test_error.rb",
    "test/unit/test_message.rb",
    "test/unit/test_store_construction.rb",
    "test/unit/test_store_crud.rb",
    "test/unit/test_store_metadata.rb",
    "test/unit/test_store_password_policy.rb",
    "test/unit/test_store_security.rb"
  ]
  s.homepage = "http://github.com/nerab/pwm"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.15"
  s.summary = "Command-line password manager"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<encryptor>, [">= 0"])
      s.add_runtime_dependency(%q<commander>, [">= 0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.3"])
    else
      s.add_dependency(%q<encryptor>, [">= 0"])
      s.add_dependency(%q<commander>, [">= 0"])
      s.add_dependency(%q<activesupport>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
    end
  else
    s.add_dependency(%q<encryptor>, [">= 0"])
    s.add_dependency(%q<commander>, [">= 0"])
    s.add_dependency(%q<activesupport>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
  end
end

